modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="gdbuax"
version="0.1.1"
displayName="Better Update"
displayURL="https://t.me/GrandRikSon"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="GreyDesh, MCreator"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.gdbuax]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



