modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="gdbuax"
version="1.0.0"
displayName="Better Update"
displayURL="https://t.me/GrandRikSon"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="GreyDesh, MCreator"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.gdbuax]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.92,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.gdbuax]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration